DELETE http://localhost:3003/api/blogs/63f2488dd0bac9063a29e34e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impvb2tlbXAiLCJpZCI6IjYzZWY4NGE5ODQ4MWMzYWQxNzJkYzM2OCIsImlhdCI6MTY3NjgyMDMzN30.BhY0tSATIbRuCgcYIi7z38-rKNDLptnndi-6npTKabo 